import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// Fully autogenerated from Documentation/Welcome — the Confluence sync
// dictates structure; labels are cleaned in docusaurus.config.ts.
const sidebars: SidebarsConfig = {
  docs: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;
